apiVersion: apps/v1
kind: Deployment
metadata:
  name: pricing-v2
  namespace: pricing
spec:
  replicas: 1
  selector:
    matchLabels:
      app: pricing
      version: v2
  template:
    metadata:
      labels:
        app: pricing
        version: v2
    spec:
      containers:
        - name: app
          image: pricing-service:latest
          imagePullPolicy: Never
          env:
            - name: APP_VERSION
              value: CUSTOMER